name: Deploy pages
on: push
jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache node modules
        id: cache-npm-core
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: core/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm-core.outputs.cache-hit != 'true' }}
        name: install node modules
        run: npm install
        working-directory: core 
      - name: build
        run: CI=false npm run build
        working-directory: core
      - uses: actions/upload-artifact@master
        with:
          name: core-build
          path: core/dist
  build-ui:
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@master
        with:
          name: core-build
          path: core/dist
      - name: cache node modules
        id: cache-npm-ui
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: web-ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm-ui.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: npm install
        working-directory: web-ui 
      - name: build
        run: npm run build
        working-directory: web-ui
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web-ui/build
